# -*- coding: utf-8 -*-
"""Metadane parametrów kotła CO - kopia z heating_service/shadow_vault.py.

Kopia, nie import: caveweb jest samodzielną usługą i integruje się z resztą
instalacji wyłącznie przez MQTT (nie ma dostępu do drzewa `cave`). Trzymamy
tylko to, co potrzebne do zbudowania interfejsu: topic, typ, zakres, jednostkę
i opis. `source_type` rozdziela nastawy (setpoint, edytowalne) od czujników
(sensor, tylko podgląd).

Przy zmianie PARAMS_HEATING w heating_service trzeba odświeżyć ten plik.
"""

__version__ = "0.1"

PARAMS = {
    'furnace_enable_setpoint': {
        'topic': 'cave/heating/setpoints/furnace_enable',
        'data_type': 'bool',
        'default': True,
        'min': False,
        'max': True,
        'unit': '',
        'desc': 'Włączenie/wyłączenie sterownika',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'furnace_temp_setpoint': {
        'topic': 'cave/heating/setpoints/furnace_temp',
        'data_type': 'int',
        'default': 60,
        'min': 52,
        'max': 72,
        'unit': '°C',
        'desc': 'Temperatura pieca (kotła CO)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'flue_gas_temp_setpoint': {
        'topic': 'cave/heating/setpoints/flue_gas_temp',
        'data_type': 'int',
        'default': 55,
        'min': 20,
        'max': 200,
        'unit': '°C',
        'desc': 'Temperatura spalin',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'dhw_temp_setpoint': {
        'topic': 'cave/heating/setpoints/dhw_temp',
        'data_type': 'int',
        'default': 55,
        'min': 30,
        'max': 75,
        'unit': '°C',
        'desc': 'Domestic hot water (DHW) temperature, ogrzewania wody użytkowej (CWU)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'return_water_temp_setpoint': {
        'topic': 'cave/heating/setpoints/return_water_temp',
        'data_type': 'int',
        'default': 45,
        'min': 30,
        'max': 75,
        'unit': '°C',
        'desc': 'Temperatura powrotu, Zapobieganie kondensacji i korozji',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'feeder_temp_setpoint': {
        'topic': 'cave/heating/setpoints/feeder_temp',
        'data_type': 'int',
        'default': 85,
        'min': 15,
        'max': 120,
        'unit': '°C',
        'desc': 'Temperatura podajnika, Ochrona przed zapłonem wstecznym w podajniku',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'pause_time_setpoint': {
        'topic': 'cave/heating/setpoints/pause_time',
        'data_type': 'int',
        'default': 120,
        'min': 30,
        'max': 300,
        'unit': 's',
        'desc': 'Czas pauzy (między karmieniami)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'feeding_time_setpoint': {
        'topic': 'cave/heating/setpoints/feeding_time',
        'data_type': 'int',
        'default': 9,
        'min': 3,
        'max': 30,
        'unit': 's',
        'desc': 'Czas podawania (karmienia)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'furnace_temp_sensor': {
        'topic': 'cave/sensors/temperature/furnace_temp',
        'data_type': 'float',
        'default': None,
        'min': 0.0,
        'max': 120.0,
        'unit': '°C',
        'desc': 'Temperatura pieca (kotła CO)',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'return_fireplace_temp_sensor': {
        'topic': 'cave/sensors/temperature/return_fireplace_temp',
        'data_type': 'float',
        'default': None,
        'min': 0.0,
        'max': 120.0,
        'unit': '°C',
        'desc': 'Temperatura na wejściu do kominka',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'flue_gas_temp_sensor': {
        'topic': 'cave/sensors/temperature/flue_gas_temp',
        'data_type': 'float',
        'default': None,
        'min': 20.0,
        'max': 200.0,
        'unit': '°C',
        'desc': 'Temperatura spalin',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'dhw_temp_sensor': {
        'topic': 'cave/sensors/temperature/dhw_temp',
        'data_type': 'float',
        'default': None,
        'min': -10.0,
        'max': 120.0,
        'unit': '°C',
        'desc': 'Domestic hot water (DHW) temperature, ogrzewania wody użytkowej (CWU)',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'return_water_temp_sensor': {
        'topic': 'cave/sensors/temperature/return_water_temp',
        'data_type': 'float',
        'default': None,
        'min': -50.0,
        'max': 150.0,
        'unit': '°C',
        'desc': 'Temperatura powrotu, Zapobieganie kondensacji i korozji',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'feeder_temp_sensor': {
        'topic': 'cave/sensors/temperature/feeder_temp',
        'data_type': 'float',
        'default': None,
        'min': -50.0,
        'max': 150.0,
        'unit': '°C',
        'desc': 'Temperatura podajnika, Ochrona przed zapłonem wstecznym w podajniku',
        'source_type': 'sensor',
        'category': 'heating',
    },
    'keeping_fire_interval_setpoint': {
        'topic': 'cave/heating/setpoints/keeping_fire_interval',
        'data_type': 'int',
        'default': 600,
        'min': 300,
        'max': 1800,
        'unit': 's',
        'desc': 'Interwał między przedmuchami podtrzymującymi (co ile sekund włączyć dmuchawę)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'keeping_fire_duration_setpoint': {
        'topic': 'cave/heating/setpoints/keeping_fire_duration',
        'data_type': 'int',
        'default': 12,
        'min': 5,
        'max': 120,
        'unit': 's',
        'desc': 'Czas trwania przedmuchu podtrzymującego (jak długo dmuchać)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'multiplicity_setpoint': {
        'topic': 'cave/heating/setpoints/multiplicity',
        'data_type': 'int',
        'default': 2,
        'min': 1,
        'max': 10,
        'unit': '',
        'desc': 'co który cykl podawać',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'fan_speed_setpoint': {
        'topic': 'cave/heating/setpoints/fan_speed',
        'data_type': 'int',
        'default': 50,
        'min': 0,
        'max': 100,
        'unit': '%',
        'desc': 'Prędkość wentylatora (dmuchawy)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'startup_temp_min_setpoint': {
        'topic': 'cave/heating/setpoints/startup_temp_min',
        'data_type': 'int',
        'default': 40,
        'min': 20,
        'max': 60,
        'unit': '°C',
        'desc': 'Minimalna temperatura startupu (limit rozgrzania)',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'startup_timeout_setpoint': {
        'topic': 'cave/heating/setpoints/startup_timeout',
        'data_type': 'int',
        'default': 10,
        'min': 0,
        'max': 60,
        'unit': 's',
        'desc': 'Maksymalny czas aby rozgrzać.',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'mixing_valve_time_setpoint': {
        'topic': 'cave/heating/setpoints/mixing_valve_time',
        'data_type': 'int',
        'default': 120,
        'min': 5,
        'max': 300,
        'unit': 's',
        'desc': 'Czas otwierania zaworu mieszającego',
        'source_type': 'setpoint',
        'category': 'heating',
    },
    'inside_temp_setpoint': {
        'topic': 'cave/heating/setpoints/inside_temp',
        'data_type': 'float',
        'default': 21.3,
        'min': 15.0,
        'max': 28.0,
        'unit': '°C',
        'desc': 'Temperatura wewnętrzna.',
        'source_type': 'setpoint',
        'category': 'heating',
    },
}


def by_source(source_type):
    """Parametry danego rodzaju w kolejności z shadow_vault."""
    return {name: meta for name, meta in PARAMS.items()
            if meta['source_type'] == source_type}


SETPOINTS = by_source('setpoint')
SENSORS = by_source('sensor')

